//! This is a common library of functions, types, and routines for use in Zig
//! projects part of the extended RandyOS Cinematic Universe.
//! This is not a library for the RandyOS ABI, but rather, a standardized set of
//! utilities and abstractions for use across the bootloader, kernel, drivers,
//! userspace applications, and, really, any Zig application because of the
//! shifting nature of the Zig stdlib or my inability to understand how it is
//! organized.  Therefore, I will have my own convenience shortcuts or alternate
//! implementations as I feel it necessary.
//!
//! * Assume the name of the library is `rstd`.
//! * Module names should not include underscores, be all lowercase, and be as
//!   short as possible with a maximum of eight chars.
//! * For logger scope names, use the underscore-delimited path of the module,
//!   e.g., `rstd_ansi` for `src/rstd/ansi.zig` and `rstd_bootinfo` for
//!   `src/rstd/bootinfo.zig`.

/// system/compiler details
pub const sysinfo = @import("builtin");

/// build options module generated by Zig build
pub const build_options = @import("build_options");

pub const ansi = @import("ansi.zig");
pub const build = @import("build.zig");
pub const machine = @import("machine.zig");
pub const file = @import("file.zig");
pub const memory = @import("memory.zig");
pub const logging = @import("logging.zig");
pub const Terminal = @import("Terminal.zig");
pub const io = @import("io.zig");

// const std = @import("std");
// const log = std.log.scoped(.rstd);

// pub fn Logger(comptime scope: @EnumLiteral()) type {
//     std.debug.print("{t}", .{ scope });
//     @panic(message: []const u8)
//     std.debug.panic(comptime format: []const u8, args: anytype)
//     // return std.log.scoped(scope);
// }
